// swift-tools-version: 5.10
//
// Consumer-facing manifest, generated by the release workflow
// (scripts/generate-release-manifest.sh). Each version tag's binary targets
// point at that release's XCFramework zips on github.com/magicx-ai/ai-autocomplete-ios/releases,
// pinned by checksum. The development manifest with source targets lives in
// the source repo.
import PackageDescription

let package = Package(
    name: "AIAutocompleteKit",
    platforms: [.iOS(.v17)],
    products: [
        .library(
            name: "AIAutocompleteCore",
            targets: ["AIAutocompleteCore"]
        ),
        .library(
            name: "AIAutocompleteUIKit",
            targets: ["AIAutocompleteUIKit", "AIAutocompleteCore"]
        ),
        .library(
            name: "AIAutocompleteSwiftUI",
            targets: ["AIAutocompleteSwiftUI", "AIAutocompleteUIKit", "AIAutocompleteCore"]
        )
    ],
    targets: [
        .binaryTarget(
            name: "AIAutocompleteCore",
            url: "https://github.com/magicx-ai/ai-autocomplete-ios/releases/download/1.4.1/AIAutocompleteCore.xcframework.zip",
            checksum: "7e228a42e473f5ec54d28becd4c4eb74db0e71cca3115c40daa714f938b6fa94"
        ),
        .binaryTarget(
            name: "AIAutocompleteUIKit",
            url: "https://github.com/magicx-ai/ai-autocomplete-ios/releases/download/1.4.1/AIAutocompleteUIKit.xcframework.zip",
            checksum: "44876917f0b4d07399c9b5f1d68603dec9c8e8a2f41cc31930ec9bc9f3ddd4aa"
        ),
        .binaryTarget(
            name: "AIAutocompleteSwiftUI",
            url: "https://github.com/magicx-ai/ai-autocomplete-ios/releases/download/1.4.1/AIAutocompleteSwiftUI.xcframework.zip",
            checksum: "f4f16f153bbdab4eefe563eae0a346f396c698b41630f621f60d7e4e1258b87c"
        )
    ]
)
