// swift-tools-version: 5.10
//
// Consumer-facing manifest, generated by the release workflow
// (scripts/generate-release-manifest.sh). Each version tag's binary targets
// point at that release's XCFramework zips on github.com/magicx-ai/ai-autocomplete-ios/releases,
// pinned by checksum. The development manifest with source targets lives in
// the source repo.
import PackageDescription

let package = Package(
    name: "AIAutocompleteKit",
    platforms: [.iOS(.v17)],
    products: [
        .library(
            name: "AIAutocompleteCore",
            targets: ["AIAutocompleteCore"]
        ),
        .library(
            name: "AIAutocompleteUIKit",
            targets: ["AIAutocompleteUIKit", "AIAutocompleteCore"]
        ),
        .library(
            name: "AIAutocompleteSwiftUI",
            targets: ["AIAutocompleteSwiftUI", "AIAutocompleteUIKit", "AIAutocompleteCore"]
        )
    ],
    targets: [
        .binaryTarget(
            name: "AIAutocompleteCore",
            url: "https://github.com/magicx-ai/ai-autocomplete-ios/releases/download/1.6.3/AIAutocompleteCore.xcframework.zip",
            checksum: "66b943ae72287b3134a88c3fa26415a5049a0c660a87cacf71c1c3c40562b1b8"
        ),
        .binaryTarget(
            name: "AIAutocompleteUIKit",
            url: "https://github.com/magicx-ai/ai-autocomplete-ios/releases/download/1.6.3/AIAutocompleteUIKit.xcframework.zip",
            checksum: "2866e348d686e37fe4b53d08313567ac4dd93ebf89367165cb2677df21d7617a"
        ),
        .binaryTarget(
            name: "AIAutocompleteSwiftUI",
            url: "https://github.com/magicx-ai/ai-autocomplete-ios/releases/download/1.6.3/AIAutocompleteSwiftUI.xcframework.zip",
            checksum: "b7d6ff04a7a8c95b563fc9da79b5832318d8f70c371b795feee52129e1e6076a"
        )
    ]
)
