// swift-tools-version: 5.10
//
// Consumer-facing manifest, generated by the release workflow
// (scripts/generate-release-manifest.sh). Each version tag's binary targets
// point at that release's XCFramework zips on github.com/magicx-ai/ai-autocomplete-ios/releases,
// pinned by checksum. The development manifest with source targets lives in
// the source repo.
import PackageDescription

let package = Package(
    name: "AIAutocompleteKit",
    platforms: [.iOS(.v17)],
    products: [
        .library(
            name: "AIAutocompleteCore",
            targets: ["AIAutocompleteCore"]
        ),
        .library(
            name: "AIAutocompleteUIKit",
            targets: ["AIAutocompleteUIKit", "AIAutocompleteCore"]
        ),
        .library(
            name: "AIAutocompleteSwiftUI",
            targets: ["AIAutocompleteSwiftUI", "AIAutocompleteUIKit", "AIAutocompleteCore"]
        )
    ],
    targets: [
        .binaryTarget(
            name: "AIAutocompleteCore",
            url: "https://github.com/magicx-ai/ai-autocomplete-ios/releases/download/1.3.0/AIAutocompleteCore.xcframework.zip",
            checksum: "b2dc695401e649408051732178f8b7a56991b411608cd250f737b039eea326d4"
        ),
        .binaryTarget(
            name: "AIAutocompleteUIKit",
            url: "https://github.com/magicx-ai/ai-autocomplete-ios/releases/download/1.3.0/AIAutocompleteUIKit.xcframework.zip",
            checksum: "8634bdc7737f4181f30228c7864037a8cd8c46b2c61e35cf735c7fb24f08443e"
        ),
        .binaryTarget(
            name: "AIAutocompleteSwiftUI",
            url: "https://github.com/magicx-ai/ai-autocomplete-ios/releases/download/1.3.0/AIAutocompleteSwiftUI.xcframework.zip",
            checksum: "2316f297990ab4d523f32405a3356070e8b4a5bbabff34c3d1df7f3592d748a2"
        )
    ]
)
